name: Test
on: [push]
jobs:
  test-default:
    needs: docker
    name: test-default
    runs-on: ubuntu-latest
    steps:
    - name: test
      uses: colutius/Telegram-Msg@main
      with:
        token: ${{ secrets.TELEGRAM_TOKEN }}
        chatid: ${{ secrets.TELEGRAM_TO_ME }}
        is_notify: false
        is_preview: false
  docker:
    name: publish docker
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ambitionecho
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v3.0.2
        with:
          ref: docker
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          file: ./Dockerfile
          tags: ambitionecho/telegram-msg:latest

